name: physicsMB

channels:
    - defaults

dependencies:
    - python>=3.6
    - setuptools
    - numpy
    - numpydoc
    - scipy
    - astropy
    - pip:
      - -e ..
      - sphinx
      - sphinx_rtd_theme
      - stsci_rtd_theme
      - sphinx_automodapi
      - periodictable
