name: physicsMB

channels:
    - astropy
    - pypi

dependencies:
    - python>=3.6
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - pip:
        - dependency_from_pip
